version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "ronschaeffer"
    assignees:
      - "ronschaeffer"
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      - dependency-name: "pre-commit"
        # We use GitHub Actions for CI/CD instead of pre-commit hooks
