repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.7.0 # Use the latest version
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0 # Use the latest version
    hooks:
      - id: isort
        args: ["--profile", "black"] # Configure isort to work with black

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0 # Use the latest version
    hooks:
      - id: flake8
        args: ["--max-line-length=88"] # Match black's line length

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5 # Use the latest version
    hooks:
      - id: codespell
        args: ["--write-changes"] # Enable auto-fix

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1 # Use the latest version
    hooks:
      - id: mypy
        additional_dependencies: [
            "types-requests", # Add required type stubs
            "types-PyYAML",
            # ... other type stubs as needed
          ]
