name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    env:
      TZ: UTC
      LANG: C.UTF-8
      PYTHONHASHSEED: "0"
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
        with:
          version: 2.1.4
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: .venv
          key: venv-${{ runner.os }}-3.11-poetry-2.1.4-extras-dev-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-3.11-poetry-2.1.4-extras-dev-
            venv-${{ runner.os }}-3.11-

      - name: Install dependencies
        run: poetry install --all-extras --no-root --no-interaction --no-ansi

      - name: Verify test tooling
        run: |
          echo "🔎 Verifying pytest availability..."
          if ! poetry run python -c "import pytest" >/dev/null 2>&1; then
            echo "⚠️  Missing pytest detected; installing dev extras..."
            poetry install --extras dev --no-root --no-interaction --no-ansi
            poetry run python -c "import pytest; print('pytest import: OK')"
          fi

      - name: Verify test tooling
        run: |
          echo "🔎 Verifying pytest and pre-commit availability..."
          if ! poetry run python -c "import pytest, pre_commit" >/dev/null 2>&1; then
            echo "⚠️  Missing test tooling detected; installing dev extras..."
            poetry install --extras dev --no-root --no-interaction --no-ansi
            poetry run python -c "import pytest, pre_commit; print('pytest/pre-commit import: OK')"
          fi

      - name: Show tool versions
        run: |
          poetry --version
          poetry run python -V
          poetry run python -c "import sys; print('venv:', sys.executable)"
          poetry run python -c "import pytest, pre_commit; print('pytest/pre-commit import: OK')"

      - name: Validate Poetry configuration
        run: poetry check

      - name: Run linting checks
        run: |
          echo "🔍 Running linting checks..."
          poetry run ruff check .
          echo "🎨 Checking code formatting..."
          poetry run ruff format --check .

      - name: Run pre-commit (skip pytest hook)
        env:
          SKIP: pytest-push
        run: |
          poetry run pre-commit run --all-files

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    env:
      TZ: UTC
      LANG: C.UTF-8
      PYTHONHASHSEED: "0"
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
        with:
          version: 2.1.4
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-poetry-2.1.4-extras-dev-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-${{ matrix.python-version }}-poetry-2.1.4-extras-dev-
            venv-${{ runner.os }}-${{ matrix.python-version }}-

      - name: Install dependencies
        run: poetry install --all-extras --no-root --no-interaction --no-ansi

      - name: Run tests
        run: |
          echo "🧪 Running test suite..."
          poetry check
          poetry run pytest --cov --cov-report=xml --cov-report=term-missing

      - name: Upload coverage reports
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage-report-${{ matrix.python-version }}
          path: coverage.xml
        if: matrix.python-version == '3.11'
